### ISSUE TITLE
Add option for pre-commit

### ISSUE THREAD

**Issue by veit** [veit/cookiecutter-namespace-template#23]
* [pre-commit](https://pre-commit.com/) offers a framework for running hooks before committing code.
* Config ``.pre-commit-config.yaml``:
    ```
    repos:
      - repo: https://github.com/psf/black
        rev: 19.10b0
        hooks:
          - id: black
            language_version: python3.7
            # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
            types: []

      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.9
        hooks:
          - id: flake8
            language_version: python3.7

      - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
        hooks:
          - id: seed-isort-config

      - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
        hooks:
          - id: isort
            additional_dependencies: [toml]
            language_version: python3.7

      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.4.0
        hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: debug-statements
    ```
